# Generated by Django 6.0.6 on 2026-07-04 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('owner_level', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'permissions': [('manage_roles', 'Can manage roles in scope'), ('manage_global_roles', 'Can manage system roles')],
                'swappable': 'SCOPED_ACCESS_ROLE_MODEL',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_role_permissions', to='auth.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to=settings.SCOPED_ACCESS_ROLE_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='scoped_roles', through='scoped_access.RolePermission', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='ScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('scope_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.SCOPED_ACCESS_ROLE_MODEL)),
                ('scope_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_assignments', 'Can manage scope assignments')],
                'swappable': 'SCOPED_ACCESS_ASSIGNMENT_MODEL',
                'indexes': [models.Index(fields=['user', 'status'], name='scoped_assign_user_status_idx'), models.Index(fields=['scope_ct', 'scope_id'], name='scoped_assign_scope_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'REVOKED'), _negated=True), fields=('user', 'role', 'level', 'scope_ct', 'scope_id'), name='scoped_access_unique_live_assignment')],
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='scoped_access_unique_role_perm'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_id__isnull', False)), fields=('name', 'owner_ct', 'owner_id'), name='scoped_access_unique_custom_role_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_id__isnull', True)), fields=('name',), name='scoped_access_unique_system_role_name'),
        ),
    ]
